version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    groups:
      development:
        patterns:
          - "pytest*"
          - "mypy*"
          - "ruff*"
          - "pre-commit*"
      data-tools:
        patterns:
          - "dlt*"
          - "sqlmesh*"
          - "duckdb*"
          - "pandas*"
      orchestration:
        patterns:
          - "dagster*"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"