-- Create schemas for all data layers
CREATE SCHEMA IF NOT EXISTS raw_ebird;
CREATE SCHEMA IF NOT EXISTS raw_noaa;
CREATE SCHEMA IF NOT EXISTS ebird;
CREATE SCHEMA IF NOT EXISTS noaa;

-- Grant privileges to databox user
GRANT ALL PRIVILEGES ON SCHEMA raw_ebird TO databox;
GRANT ALL PRIVILEGES ON SCHEMA raw_noaa TO databox;
GRANT ALL PRIVILEGES ON SCHEMA ebird TO databox;
GRANT ALL PRIVILEGES ON SCHEMA noaa TO databox;

-- Grant default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA raw_ebird GRANT ALL ON TABLES TO databox;
ALTER DEFAULT PRIVILEGES IN SCHEMA raw_noaa GRANT ALL ON TABLES TO databox;
ALTER DEFAULT PRIVILEGES IN SCHEMA ebird GRANT ALL ON TABLES TO databox;
ALTER DEFAULT PRIVILEGES IN SCHEMA noaa GRANT ALL ON TABLES TO databox;
