-- Create schemas for all data layers
CREATE SCHEMA IF NOT EXISTS raw_ebird;
CREATE SCHEMA IF NOT EXISTS raw_noaa;
CREATE SCHEMA IF NOT EXISTS ebird_staging;
CREATE SCHEMA IF NOT EXISTS noaa_staging;
CREATE SCHEMA IF NOT EXISTS ebird;
CREATE SCHEMA IF NOT EXISTS noaa;
CREATE SCHEMA IF NOT EXISTS analytics;

-- Grant privileges to databox user
GRANT ALL PRIVILEGES ON SCHEMA raw_ebird TO databox;
GRANT ALL PRIVILEGES ON SCHEMA raw_noaa TO databox;
GRANT ALL PRIVILEGES ON SCHEMA ebird_staging TO databox;
GRANT ALL PRIVILEGES ON SCHEMA noaa_staging TO databox;
GRANT ALL PRIVILEGES ON SCHEMA ebird TO databox;
GRANT ALL PRIVILEGES ON SCHEMA noaa TO databox;
GRANT ALL PRIVILEGES ON SCHEMA analytics TO databox;

-- Grant default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA raw_ebird GRANT ALL ON TABLES TO databox;
ALTER DEFAULT PRIVILEGES IN SCHEMA raw_noaa GRANT ALL ON TABLES TO databox;
ALTER DEFAULT PRIVILEGES IN SCHEMA ebird_staging GRANT ALL ON TABLES TO databox;
ALTER DEFAULT PRIVILEGES IN SCHEMA noaa_staging GRANT ALL ON TABLES TO databox;
ALTER DEFAULT PRIVILEGES IN SCHEMA ebird GRANT ALL ON TABLES TO databox;
ALTER DEFAULT PRIVILEGES IN SCHEMA noaa GRANT ALL ON TABLES TO databox;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT ALL ON TABLES TO databox;
