[project]
name = "databox"
version = "0.1.0"
description = "World-class data project using dlt for ingestion and sqlmesh for transformation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlt[duckdb]>=1.14.1",
    "sqlmesh>=0.204.0",
    "duckdb>=1.1.3",
    "pandas>=2.2.3",
    "pyarrow>=18.1.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "pydantic>=2.10.4",
    "streamlit>=1.41.1",
    "rich>=13.9.4",
    "pendulum>=3.0.0",
]

[project.scripts]
databox = "databox.cli:main"

[build-system]
requires = ["setuptools>=70.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["databox"]

[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E", "F", "I", "N", "UP", "B", "C90"]

