connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://polaris:8181/api/catalog
iceberg.rest-catalog.warehouse=${ENV:DATABOX_ICEBERG_CATALOG}
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.credential=${ENV:DATABOX_POLARIS_CLIENT_ID}:${ENV:DATABOX_POLARIS_CLIENT_SECRET}
iceberg.rest-catalog.oauth2.scope=PRINCIPAL_ROLE:ALL
iceberg.rest-catalog.oauth2.server-uri=http://polaris:8181/api/catalog/v1/oauth/tokens
iceberg.rest-catalog.view-endpoints-enabled=true
iceberg.rest-catalog.vended-credentials-enabled=false
fs.s3.enabled=true
s3.region=${ENV:AWS_REGION}
