gateways:
  postgres:
    connection:
      type: postgres
      host: ${POSTGRES_HOST:-localhost}
      port: 5432
      database: ${POSTGRES_DB:-databox}
      user: ${POSTGRES_USER:-databox}
      password: ${POSTGRES_PASSWORD:-databox}

default_gateway: postgres

model_defaults:
  dialect: postgres
  start: 2025-07-25
  cron: "@daily"

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
