gateways:
  duckdb:
    connection:
      type: duckdb
      database: ../../data/databox.db

default_gateway: duckdb

model_defaults:
  dialect: duckdb
  start: 2025-07-25
  cron: "@daily"

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
