dataset: databox/usgs_staging/stg_usgs_daily_values

columns:
  - name: site_no
    checks:
      - missing:
          must_be: 0
  - name: observation_date
    checks:
      - missing:
          must_be: 0
  - name: parameter_cd
    checks:
      - missing:
          must_be: 0
  - name: value

checks:
  - row_count:
      must_be_greater_than: 0
  - freshness:
      column: loaded_at
      threshold:
        unit: hour
        must_be_less_than: 25
