MODEL (
  name birding_agent.gbif_occurrence_evidence,
  kind VIEW,
  description 'Planner-ready GBIF bird occurrence evidence with taxonomy, location, license, and source provenance.',
  grants (select_ = ['staging_reader', 'domain_reader', 'analyst'])
);

SELECT
  md5('birding_agent|gbif_occurrence|' || CAST(key AS VARCHAR)) AS occurrence_evidence_id,
  'gbif' AS evidence_source,
  'raw_gbif.occurrences' AS source_table,
  CAST(key AS VARCHAR) AS source_record_id,
  key AS gbif_key,
  gbif_id,
  occurrence_id,
  dataset_key,
  publishing_org_key,
  scientific_name,
  accepted_scientific_name,
  vernacular_name AS common_name,
  family,
  genus,
  species,
  taxon_rank,
  taxon_key,
  accepted_taxon_key,
  decimal_latitude AS latitude,
  decimal_longitude AS longitude,
  coordinate_uncertainty_in_meters,
  country,
  country_code,
  state_province,
  locality,
  event_date AS event_date_text,
  year,
  month,
  day,
  basis_of_record,
  occurrence_status,
  establishment_means,
  license,
  references AS source_reference_url,
  last_interpreted,
  last_crawled,
  last_parsed,
  _source_url,
  _query_country_code,
  _query_state_province,
  _query_taxon_key,
  _loaded_at::TIMESTAMP AS loaded_at,
  _dlt_load_id AS dlt_load_id,
  _dlt_id AS dlt_id
FROM raw_gbif.occurrences
WHERE key IS NOT NULL
