MODEL (
  name birding_agent.xeno_canto_media_evidence,
  kind VIEW,
  description 'Planner-ready Xeno-canto bird sound metadata with media links, license, attribution, and provenance.',
  grants (select_ = ['staging_reader', 'domain_reader', 'analyst'])
);

SELECT
  md5('birding_agent|xeno_canto_recording|' || id) AS media_evidence_id,
  'xeno_canto' AS evidence_source,
  'raw_xeno_canto.recordings' AS source_table,
  id AS source_record_id,
  id AS recording_id,
  genus,
  species,
  subspecies,
  group_name,
  english_name,
  recordist,
  country,
  locality,
  latitude,
  longitude,
  altitude,
  recording_type,
  sex,
  stage,
  method,
  recording_url,
  audio_file_url,
  file_name,
  sonogram,
  oscillogram,
  license,
  quality,
  length,
  recording_time,
  recording_date,
  uploaded_at,
  also_species,
  remarks,
  bird_seen,
  animal_seen,
  playback_used,
  temperature,
  registration_number,
  automatic_recording,
  device,
  microphone,
  _source_url,
  _query,
  _query_page,
  _loaded_at::TIMESTAMP AS loaded_at,
  _dlt_load_id AS dlt_load_id,
  _dlt_id AS dlt_id
FROM raw_xeno_canto.recordings
WHERE id IS NOT NULL
