"""Render docs/cost.md from analytics.mart_cost_summary.

Outputs:
    docs/cost.md             — markdown body with chart + 30-day table
    docs/images/cost/daily.png — 30-day stacked chart of compute + storage

Exit: 0 always. Falls back to a placeholder page if the mart is missing or
empty so fresh checkouts still render deployable docs.
"""

from __future__ import annotations

import sys
from pathlib import Path

import duckdb
import matplotlib.pyplot as plt
import pandas as pd
from databox.config.settings import settings

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = PROJECT_ROOT / "docs"
IMAGES_DIR = DOCS_DIR / "images" / "cost"
OUT_MD = DOCS_DIR / "cost.md"
CHART_PATH = IMAGES_DIR / "daily.png"


def fetch_summary() -> pd.DataFrame:
    con = duckdb.connect(settings.database_path, read_only=True)
    try:
        return con.execute(
            """
            SELECT day_date, backend, query_count, compute_seconds,
                   storage_bytes, motherduck_cost_usd
            FROM analytics.mart_cost_summary
            ORDER BY day_date
            """
        ).df()
    finally:
        con.close()


def render_chart(df: pd.DataFrame) -> None:
    IMAGES_DIR.mkdir(parents=True, exist_ok=True)
    recent = df.tail(30).copy()
    recent["storage_mb"] = recent["storage_bytes"] / 1_048_576

    fig, ax_left = plt.subplots(figsize=(9, 4.5))
    ax_left.plot(
        recent["day_date"],
        recent["compute_seconds"],
        color="#2a9d8f",
        marker="o",
        label="Compute (s)",
    )
    ax_left.set_ylabel("Compute seconds", color="#2a9d8f")
    ax_left.tick_params(axis="y", labelcolor="#2a9d8f")
    ax_left.set_xlabel("Day")

    ax_right = ax_left.twinx()
    ax_right.plot(
        recent["day_date"], recent["storage_mb"], color="#e76f51", marker="s", label="Storage (MB)"
    )
    ax_right.set_ylabel("Storage (MB)", color="#e76f51")
    ax_right.tick_params(axis="y", labelcolor="#e76f51")

    fig.autofmt_xdate()
    fig.suptitle("Databox 30-day usage")
    fig.tight_layout()
    fig.savefig(CHART_PATH, dpi=110, bbox_inches="tight")
    plt.close(fig)


def render_table(df: pd.DataFrame) -> str:
    recent = df.tail(30).copy()
    recent["storage_mb"] = (recent["storage_bytes"] / 1_048_576).round(2)
    recent["cost_usd"] = recent["motherduck_cost_usd"].round(4)
    cols = ["day_date", "backend", "query_count", "compute_seconds", "storage_mb", "cost_usd"]
    return recent[cols].to_markdown(index=False, floatfmt=".2f")


PLACEHOLDER = """# Cost & usage

The `analytics.mart_cost_summary` asset has not materialised yet. Run
`uv run dagster asset materialize --select mart_cost_summary` (or wait
for the daily schedule) to populate this page.

See the [cost model](#cost-model) below for what the numbers mean.
"""


COST_MODEL_BODY = """
## Cost model

**MotherDuck backend.** `compute_seconds` comes from
`MD_INFORMATION_SCHEMA.QUERY_HISTORY`; `storage_bytes` from
`MD_INFORMATION_SCHEMA.STORAGE_INFO_HISTORY` (Business plan gate — the
asset falls back to a single zero-row if the views are unreachable).
`motherduck_cost_usd` is `compute_seconds *
MOTHERDUCK_COST_PER_COMPUTE_SECOND` with the rate hardcoded in
`packages/databox/databox/orchestration/domains/analytics.py` at
MotherDuck's current public "Standard" price. **Update that constant
when MotherDuck's price changes** — there is no pricing API to pull
from.

**Local backend.** `storage_bytes` is the sum of `os.stat(...).st_size`
for every `data/*.duckdb` file. `compute_seconds` and `query_count` are
zeroed out; `motherduck_cost_usd` is NULL. Local is essentially free —
this page exists so forkers can still see disk-growth trends.

## Extending alerts

The ticket scope does not include budget alerts. If you want one, pair
the `freshness_violation_sensor` pattern from `docs/freshness.md` with a
threshold on the freshest `motherduck_cost_usd` row. A minimal sketch
lives under
[`docs/freshness.md#wiring-to-an-alert-channel`](freshness.md#wiring-to-an-alert-channel).
"""


def render(df: pd.DataFrame) -> str:
    if df.empty:
        return PLACEHOLDER + COST_MODEL_BODY

    latest = df.iloc[-1]
    storage_mb = (latest["storage_bytes"] or 0) / 1_048_576
    cost = latest["motherduck_cost_usd"]
    cost_line = f"${float(cost):.4f}" if pd.notna(cost) else "n/a (local backend)"

    header = f"""# Cost & usage

Daily snapshot of compute and storage consumption from
`analytics.mart_cost_summary`. Regenerated by
`scripts/render_cost_page.py`; do not hand-edit.

**Backend:** `{latest["backend"]}`
**Latest day:** `{latest["day_date"]}`
**Storage:** {storage_mb:.2f} MB
**Queries today:** {int(latest["query_count"] or 0)}
**Compute today:** {float(latest["compute_seconds"] or 0.0):.2f} s
**Cost today:** {cost_line}

![30-day usage](images/cost/daily.png)

## Last 30 days

{render_table(df)}
"""
    return header + COST_MODEL_BODY


def main() -> int:
    try:
        df = fetch_summary()
    except Exception as exc:  # noqa: BLE001
        print(f"cost mart not queryable ({exc}); writing placeholder", file=sys.stderr)
        OUT_MD.write_text(PLACEHOLDER + COST_MODEL_BODY)
        return 0

    if not df.empty:
        render_chart(df)

    OUT_MD.write_text(render(df))
    print(f"wrote {OUT_MD.relative_to(PROJECT_ROOT)} ({len(df)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
