name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.12"

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e .

      - name: Run ruff linting
        run: |
          source .venv/bin/activate
          ruff check . --output-format=github

      - name: Run ruff formatting check
        run: |
          source .venv/bin/activate
          ruff format . --check

  security-check:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create virtual environment
        run: |
          uv venv
          uv pip install -e .

      - name: Check for secrets
        run: |
          python scripts/check_secrets.py .

      - name: Run pip-audit
        run: |
          source .venv/bin/activate
          uv pip install pip-audit
          pip-audit
